title: LocalMinimum.us
description: Resources, reading and notes on AI in surgical care.
author: David P. Stonko, MD, MS
url: https://localminimum.us
baseurl: ""
markdown: kramdown
kramdown:
  input: GFM
permalink: /library/:year/:month/:title/
plugins:
  - jekyll-feed
feed:
  path: feed.xml
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
exclude:
  - README.md
