title: AI and Surgery Interest Group
description: Johns Hopkins Department of Surgery. Resources, reading and notes on AI in surgical care.
author: David P. Stonko, MD, MS
url: https://davidstonko.github.io
baseurl: /ai-surgery
markdown: kramdown
kramdown:
  input: GFM
permalink: /library/:year/:month/:title/
plugins:
  - jekyll-feed
feed:
  path: feed.xml
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
exclude:
  - README.md
